### ISSUE TITLE
Handle timeout and other possible `HTTPoison` errors

### ISSUE THREAD

**Issue by vladimir-e** [nsweeting/shopify#37]
Hello. First of all thanks a lot for making this lib!

I faced a problem while using the lib and would like to discuss a solution, so I can submit a PR fixing it.

During long-running process of importing products via Shopify API, we occasionally get the following error:

``` elixir
Shopify.Product.create(session, payload)

%FunctionClauseError{args: nil, arity: 2, clauses: nil, function: :handle_response, kind: nil, module: Shopify.Adapters.HTTP}
 ```

It happens here:

https://github.com/nsweeting/shopify/blob/master/lib/shopify/adapters/http.ex
```elixir
defmodule Shopify.Adapters.HTTP do
  # ...
  def handle_response({:ok, %HTTPoison.Response{status_code: code, body: body}}, resource) do
    Shopify.Response.new(code, body, resource)
  end
```

I believe we could add another clause for `handle_response` catching everything else and return something like:

``` elixir
  def handle_response(response, resource) do
    {:error, response, resource}
  end
```

Maybe it would be worthwhile creating `Shopify.Error` to "standardize" the error format.

Please let me know what you think? If I at least start on adding a clause for `handle_response` figuring out the details of implementation as I go, would you accept such PR?

Currently I use this workaround:

``` elixir
    try do
      result = Product.create(session, payload)

    rescue
      # Catch unhandled timeout error in Shopify lib
      e in FunctionClauseError ->
        {:error, record, e}
    end
```

**Comment by Ninigi** [comment]
First of all, thanks for the work you already put into thinking about this issue, really appreciated!

You are absolutely right, there are unhandled errors that will sometimes break an app with a pretty unclear error message... I would love to put some work into that and handle known errors more gracefully.

Right now, according to the documentation, the resource methods are supposed to return `{:ok, %Shopify.Response{}}` or `{:error, %Shopify.Response{}}`, I would like to stick to this format of a 2 element tuple and either `:ok` or `:error`, but we can introduce a `%Shopify.Error{}` struct.

Regarding the implementation:
I think returning `{:error, %Shopify.Error{}}` would bubble up, so guess your approach would work 👍 
We would have to put some thought into the error fields, since we might want to use it for the errors returned by the shopify api as well, for that we would need a `data` and a `code` field to make it backwards compatible.

If you want to take a shot at it, I will be more than happy to review and merge 🔥
