### ISSUE TITLE
Add Versioning Support

### ISSUE THREAD

**Issue by nsweeting** [nsweeting/shopify#72]
As per the [recent announcement](https://www.shopify.com/partners/blog/api-versioning-at-shopify), we will need to add support for versioning.

The shopify session struct should most likely carry this information around. I'm envisioning a default version could be set in the application config. But we could also add a `Shopify.Session.put_version/2` function that allows one to explicitly set a new version.

**Comment by Ninigi** [comment]
@nsweeting Another question is, how are we going to handle outdated/updated resource structs? Are we going to keep outdated structs around to support different versions? Would we namespace them then (that would probably mess with pattern matching though)?

**Comment by Ninigi** [comment]
@nsweeting I thought about the issue a little more, and I realized that using maps instead of structs would get rid of all problems and would also allow for a seamless graphql integration.

I absolutely love the key safety structs provide, so I would like to keep that even if we decided to ditch them for this library. So we my idea would be to extract the structs into a different library, and make it an optional dependency.

**Comment by nsweeting** [comment]
Yeah I've been thinking about providing bare maps for a while now. It also prevents issues with missing attributes.

I'm wondering how other libraries will be handling the versioning. The ruby library uses ActiveResource, so that is much more dynamic in nature. The shopify go library would be a bit more like how elixir works. Technically, we could just maintain both old and new attributes in the same struct. It really depends on how complicated shopify ends up making the difference in versions.

Not sure about the extraction of the structs. Actually using them in reference to responses would get pretty complicated.

Will need to think on this a bit more...

**Comment by pyramind10** [comment]
I like the idea of using maps or at least have the option to use a bare maps instead of structs. The scope of api changes is still unknown but updating/deprecating versioned structs on a rolling basis might become a maintenance issue. Using bare maps eliminates a lot of the questions around how manage versions. A developer can reference the Shopify Api docs for relevant fields. 

Looking at the official ruby/python libs they now require a version when initializing a session, I think this lib could adopt that. Ideally there would also be a way to dynamically make calls to various versions. ie. 

`Shopify.Session.put_version/2` 

or even something like

` Shopify.Product.find(session, id, api_version: 'unstable')`
` Shopify.Product.find(session, id, api_version: '2019-04')`

That's my 2 cents. Hope that helps.
